// PDF Export utility for job data - Hybrid Approach
// Page 1: HTML with html2canvas for beautiful design
// Page 2+: Text-based for searchable job description
import { JobData } from '@/types';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export class PDFExporter {
  // No need to preload libraries - they're bundled
  public static async preloadLibraries(): Promise<void> {
    console.log('✅ PDF libraries bundled with extension');
  }

  public static async exportJobDataAsPDF(jobData: JobData): Promise<void> {
    try {
      console.log('🚀 Starting PDF export for job:', jobData.position);

      // Create PDF
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();

      console.log('📄 Creating beautiful first page with HTML rendering...');

      // Page 1: Render beautiful HTML summary
      await this.renderHtmlSummaryPage(pdf, jobData);

      // Page 2+: Add searchable text-based description if exists
      if (jobData.description && jobData.description.trim()) {
        console.log('📄 Adding searchable job description...');
        pdf.addPage();
        this.addJobDescriptionPage(pdf, jobData.description);
      }

      // Save the PDF
      const fileName = this.generateFileName(jobData);
      console.log('💾 Saving PDF as:', fileName);
      pdf.save(fileName);
      console.log('✅ PDF export completed successfully');

    } catch (error) {
      console.error('❌ Error generating PDF:', error);
      throw new Error('Failed to generate PDF: ' + (error instanceof Error ? error.message : String(error)));
    }
  }

  // Render Page 1 with beautiful HTML layout
  private static async renderHtmlSummaryPage(pdf: jsPDF, jobData: JobData): Promise<void> {
    // Create temporary container for HTML rendering
    const container = document.createElement('div');
    container.style.width = '210mm'; // A4 width
    container.style.padding = '20px';
    container.style.backgroundColor = 'white';
    container.style.fontFamily = 'Arial, sans-serif';
    container.innerHTML = this.generateJobSummaryHTML(jobData);
    
    // Position off-screen
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    document.body.appendChild(container);

    try {
      // Convert HTML to canvas
      const canvas = await html2canvas(container, {
        scale: 2, // High quality
        useCORS: true,
        backgroundColor: '#ffffff',
        logging: false
      });

      // Calculate dimensions to fit on PDF page
      const imgData = canvas.toDataURL('image/png');
      const imgWidth = 210; // A4 width in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      // Add image to PDF
      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      
      console.log('✅ HTML summary page rendered successfully');
    } finally {
      // Always remove the temporary container
      document.body.removeChild(container);
    }
  }

  // Generate beautiful HTML for Page 1 summary
  private static generateJobSummaryHTML(jobData: JobData): string {
    const formatDate = (dateString: string | null) => {
      if (!dateString) return 'Not specified';
      return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    };

    const formatSalary = (jobData: JobData) => {
      if (jobData.salary) {
        return jobData.salary;
      }
      if (jobData.salary_min && jobData.salary_max) {
        return `$${jobData.salary_min.toLocaleString()} - $${jobData.salary_max.toLocaleString()} ${jobData.salary_type || 'per year'}`;
      }
      return 'Not specified';
    };

    return `
      <div style="max-width: 100%; font-family: Arial, sans-serif;">
        <!-- Header -->
        <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #e5e7eb; padding-bottom: 20px;">
          <h1 style="color: #1f2937; font-size: 28px; margin: 0 0 10px 0; font-weight: bold;">Job Information</h1>
          <p style="color: #6b7280; font-size: 16px; margin: 0;">Generated by JOT Snatcher Extension</p>
        </div>

        <!-- Job Details Section -->
        <div style="margin-bottom: 25px;">
          <h2 style="color: #1f2937; font-size: 20px; margin: 0 0 15px 0; font-weight: bold; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px;">Job Details</h2>
          
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Position</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${jobData.position || 'Not specified'}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Company</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${jobData.organization || 'Not specified'}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Location</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${jobData.location || 'Not specified'}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Salary</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${formatSalary(jobData)}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Job Type</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${jobData.type || 'Not specified'}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Work Environment</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${jobData.environment || 'Not specified'}</p>
            </div>
          </div>
        </div>

        <!-- Job Information Section -->
        <div style="margin-bottom: 25px;">
          <h2 style="color: #1f2937; font-size: 20px; margin: 0 0 15px 0; font-weight: bold; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px;">Job Information</h2>
          
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Source</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${jobData.job_site || 'Unknown'}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Stage</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${jobData.stage || 'Saved'}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Date Saved</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${formatDate(jobData.date_saved)}</p>
            </div>
            
            <div>
              <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Date Posted</h3>
              <p style="color: #1f2937; font-size: 14px; margin: 0; word-wrap: break-word;">${formatDate(jobData.date_posted)}</p>
            </div>
          </div>
        </div>

        <!-- Job Links Section -->
        <div style="margin-bottom: 25px;">
          <h2 style="color: #1f2937; font-size: 20px; margin: 0 0 15px 0; font-weight: bold; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px;">Job Links</h2>
          
          <div style="margin-bottom: 15px;">
            <h3 style="color: #374151; font-size: 16px; margin: 0 0 8px 0; font-weight: bold;">Job Posting URL</h3>
            <p style="color: #2563eb; font-size: 14px; margin: 0; word-wrap: break-word; word-break: break-all;">${jobData.job_posting_url || jobData.link || 'Not specified'}</p>
          </div>
        </div>

        <!-- Footer -->
        <div style="margin-top: 30px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center;">
          <p style="color: #6b7280; font-size: 12px; margin: 0;">Generated on ${new Date().toLocaleString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
          })} by JOT Snatcher Extension</p>
        </div>
      </div>
    `;
  }

  // Add Page 2+ with searchable text-based job description
  private static addJobDescriptionPage(pdf: jsPDF, description: string): void {
    const marginInches = 0.5;
    const marginMM = marginInches * 25.4; // Convert to mm
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const contentWidth = pdfWidth - (marginMM * 2);
    const contentHeight = pdfHeight - (marginMM * 2);
    
    let currentY = marginMM;
    const lineHeight = 6; // mm
    const fontSize = 12;
    const headerFontSize = 18;

    // Add page header
    pdf.setFontSize(headerFontSize);
    pdf.setFont('helvetica', 'bold');
    const headerText = 'Job Description';
    const headerWidth = pdf.getTextWidth(headerText);
    const centerX = marginMM + (contentWidth / 2) - (headerWidth / 2);
    pdf.text(headerText, centerX, currentY);
    currentY += lineHeight * 2;

    // Add horizontal line
    pdf.setLineWidth(0.3);
    pdf.setDrawColor(128, 128, 128);
    pdf.line(marginMM, currentY, marginMM + contentWidth, currentY);
    currentY += lineHeight * 2;

    // Add description text
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', 'normal');

    // Strip HTML tags and decode HTML entities from description
    const cleanDescription = this.stripHtml(description);

    // Split description into lines that fit within content width
    const lines = pdf.splitTextToSize(cleanDescription, contentWidth);
    
    for (const line of lines) {
      // Check if we need a new page
      if (currentY + lineHeight > marginMM + contentHeight - 20) {
        pdf.addPage();
        currentY = marginMM;
        this.addPageFooter(pdf, marginMM, contentWidth, contentHeight);
      }
      
      pdf.text(line, marginMM, currentY);
      currentY += lineHeight;
    }

    // Add footer to last page
    this.addPageFooter(pdf, marginMM, contentWidth, contentHeight);
  }

  // Add page footer with page number
  private static addPageFooter(pdf: jsPDF, marginMM: number, contentWidth: number, contentHeight: number): void {
    const footerY = marginMM + contentHeight + 5;
    const pageNumber = (pdf as any).internal.getCurrentPageInfo().pageNumber;
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    const pageText = `Page ${pageNumber}`;
    const textWidth = pdf.getTextWidth(pageText);
    const centerX = marginMM + (contentWidth / 2) - (textWidth / 2);
    
    pdf.text(pageText, centerX, footerY);
  }

  // Strip HTML tags and decode HTML entities
  private static stripHtml(html: string): string {
    // Create a temporary div element to parse HTML
    const temp = document.createElement('div');
    temp.innerHTML = html;
    
    // Get text content (automatically strips tags and decodes entities)
    let text = temp.textContent || temp.innerText || '';
    
    // Clean up excessive whitespace and newlines
    text = text
      .replace(/\n\s*\n\s*\n/g, '\n\n') // Replace 3+ newlines with 2
      .replace(/[ \t]+/g, ' ') // Replace multiple spaces/tabs with single space
      .trim();
    
    return text;
  }

  // Generate filename with company name and date
  private static generateFileName(jobData: JobData): string {
    const cleanCompanyName = jobData.organization
      .replace(/[^a-zA-Z0-9\s-]/g, '')
      .replace(/\s+/g, '_')
      .substring(0, 50);
    
    const now = new Date();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    const year = String(now.getFullYear()).slice(-2);
    
    return `${cleanCompanyName}-${month}_${day}_${year}.pdf`;
  }
}
